// Constant variables for action creator and Reducer's

//MAINCATEGORY 
export const CREATE_MAINCATEGORY = "CREATE_MAINCATEGORY";
export const CREATE_MAINCATEGORY_RED = "CREATE_MAINCATEGORY_RED";
export const GET_MAINCATEGORY = "GET_MAINCATEGORY";
export const GET_MAINCATEGORY_RED = "GET_MAINCATEGORY_RED";
export const UPDATE_MAINCATEGORY = "UPDATE_MAINCATEGORY";
export const UPDATE_MAINCATEGORY_RED = "UPDATE_MAINCATEGORY_RED";
export const DELETE_MAINCATEGORY = "DELETE_MAINCATEGORY";
export const DELETE_MAINCATEGORY_RED = "DELETE_MAINCATEGORY_RED";

//SUBCATEGORY

export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";
export const CREATE_SUBCATEGORY_RED = "CREATE_SUBCATEGORY_RED";
export const GET_SUBCATEGORY = "GET_SUBCATEGORY";
export const GET_SUBCATEGORY_RED = "GET_SUBCATEGORY_RED";
export const UPDATE_SUBCATEGORY = "UPDATE_SUBCATEGORY";
export const UPDATE_SUBCATEGORY_RED = "UPDATE_SUBCATEGORY_RED";
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY";
export const DELETE_SUBCATEGORY_RED = "DELETE_SUBCATEGORY_RED";

//TESTIMONIAL

export const CREATE_TESTIMONIAL = "CREATE_TESTIMONIAL";
export const CREATE_TESTIMONIAL_RED = "CREATE_TESTIMONIAL_RED";
export const GET_TESTIMONIAL = "GET_TESTIMONIAL";
export const GET_TESTIMONIAL_RED = "GET_TESTIMONIAL_RED";
export const UPDATE_TESTIMONIAL = "UPDATE_TESTIMONIAL";
export const UPDATE_TESTIMONIAL_RED = "UPDATE_TESTIMONIAL_RED";
export const DELETE_TESTIMONIAL = "DELETE_TESTIMONIAL";
export const DELETE_TESTIMONIAL_RED = "DELETE_TESTIMONIAL_RED";

//CHECKOUT

export const CREATE_CHECKOUT = "CREATE_CHECKOUT";
export const CREATE_CHECKOUT_RED = "CREATE_CHECKOUT_RED";
export const GET_CHECKOUT = "GET_CHECKOUT";
export const GET_CHECKOUT_RED = "GET_CHECKOUT_RED";
export const UPDATE_CHECKOUT = "UPDATE_CHECKOUT";
export const UPDATE_CHECKOUT_RED = "UPDATE_CHECKOUT_RED";
export const DELETE_CHECKOUT = "DELETE_CHECKOUT";
export const DELETE_CHECKOUT_RED = "DELETE_CHECKOUT_RED";

//PROPERTY

export const CREATE_PROPERTY = "CREATE_PROPERTY";
export const CREATE_PROPERTY_RED = "CREATE_PROPERTY_RED";
export const GET_PROPERTY = "GET_PROPERTY";
export const GET_PROPERTY_RED = "GET_PROPERTY_RED";
export const UPDATE_PROPERTY = "UPDATE_PROPERTY";
export const UPDATE_PROPERTY_RED = "UPDATE_PROPERTY_RED";
export const DELETE_PROPERTY = "DELETE_PROPERTY";
export const DELETE_PROPERTY_RED = "DELETE_PROPERTY_RED";

//CONTACT US
export const CREATE_CONTACT = "CREATE_CONTACT";
export const CREATE_CONTACT_RED = "CREATE_CONTACT_RED";
export const GET_CONTACT = "GET_CONTACT";
export const GET_CONTACT_RED = "GET_CONTACT_RED";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const UPDATE_CONTACT_RED = "UPDATE_CONTACT_RED";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const DELETE_CONTACT_RED = "DELETE_CONTACT_RED";

//USERS
export const CREATE_USERS = "CREATE_USERS";
export const CREATE_USERS_RED = "CREATE_USERS_RED";
export const GET_USERS = "GET_USERS";
export const GET_USERS_RED = "GET_USERS_RED";
export const UPDATE_USERS = "UPDATE_USERS";
export const UPDATE_USERS_RED = "UPDATE_USERS_RED";
export const DELETE_USERS = "DELETE_USERS";
export const DELETE_USERS_RED = "DELETE_USERS_RED";

